### ISSUE TITLE
Monospace block changes in The Lounge 4.2.0 causes MOTD to be shown incorrectly

### ISSUE THREAD

**Issue by sadiepowell** [thelounge/thelounge-theme-zenburn#13]
In thelounge/thelounge#3962 the MOTD data-type value was changed from "motd" to "monospace_block" because of the addition of monospace HELP/INFO output. This theme has not yet been updated for this change so the MOTD shows as light text on a light background when using The Lounge 4.2.0.

Applying the following custom CSS fixes this for me but I'm not familiar enough with the codebase to know if other changes need to happen too:

```css
#chat .msg[data-type="monospace_block"] .text {
  background: #333;
}
```
